Repository googleapis/java-grafeas, pull requests merged in 2021-05, with the labels that each got.

#298 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: none

#299 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: containeranalysis, automerge, cla: yes

#300 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#306 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#307 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, cla: yes

#308 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#310 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#314 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: containeranalysis, automerge, cla: yes, context: full

#315 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: containeranalysis, automerge, cla: yes
