Repository googleapis/java-grafeas, pull requests merged in 2021-08, with the labels that each got.

#342 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, automerge, context: full, api: containeranalysis

#348 feat!: release gapic-generator-java v2.0.0
  src/main/java/io/grafeas/v1/GrafeasClient.java
  src/main/java/io/grafeas/v1/GrafeasSettings.java
  src/main/java/io/grafeas/v1/stub/GrafeasStubSettings.java
  src/main/java/io/grafeas/v1/stub/GrpcGrafeasStub.java
  synth.metadata
Labels: cla: yes, context: full, api: containeranalysis

#353 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, automerge, api: containeranalysis

#354 chore: remove distribution management section
  pom.xml
Labels: cla: yes, api: containeranalysis

#355 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge, api: containeranalysis

#358 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, automerge, context: full, api: containeranalysis
