Repository googleapis/java-grafeas, pull requests merged in 2021-09, with the labels that each got.

#371 build(java): update renovate config to mark conformance tests as a test commit type
  .github/workflows/ci.yaml
  renovate.json
  synth.metadata
Labels: cla: yes, context: full, api: containeranalysis

#377 chore: remove linkage monitor check
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge, api: containeranalysis

#376 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: containeranalysis

#374 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full, api: containeranalysis

#383 chore: re-generated to pick up changes from synthtool
  .github/trusted-contribution.yml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, api: containeranalysis, context: partial

#392 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, automerge, api: containeranalysis

#393 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, context: full, api: containeranalysis

#394 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge, api: containeranalysis

#395 build: add jdk 17 to java units and dependency builds
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full, api: containeranalysis
